### ISSUE TITLE
Order by > Bad behaviour

### ISSUE THREAD

**Issue by Moujimouja** [Centreon-Widgets/centreon-widget-host-monitoring#4]
When setting Order by parameter to Duration ASC, the order by is DESC (ofc when setting DESC, the order by is ASC)

![image](https://cloud.githubusercontent.com/assets/6620287/11899546/f5dd6388-a59f-11e5-95d8-90a3fa07d9fa.png)

**Comment by querwin** [comment]
Problem when order by hostname : 
PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/widgets/host-monitoring/src/index.php on line 223
