### ISSUE TITLE
CUSTOM VIEW / ACTION URL & HARD STATE DURATION

### ISSUE THREAD

**Issue by Jordan91** [Centreon-Widgets/centreon-widget-host-monitoring#5]
Hi,

In the lastest version of Centreon 2.7 , i can't use the Action URL in this menu (custom view), on the  monitoring is't ok. 
IN the same menu the HARD STATE DURATION , is not enable even if it propose.

![-centreon -custom view](https://cloud.githubusercontent.com/assets/16045498/11951624/ba464114-a892-11e5-99dd-5ed073dd981f.jpg)
![-centreon -custom view_1](https://cloud.githubusercontent.com/assets/16045498/11951626/bc520cfe-a892-11e5-97a3-31e810517291.jpg)
![-centreon -custom view_2](https://cloud.githubusercontent.com/assets/16045498/11951631/be0eb27c-a892-11e5-992c-4426e081a6f0.jpg)

**Comment by querwin** [comment]
When I click on the Action URL, the result is "about:blank"
