### ISSUE TITLE
action_url and notes_url

### ISSUE THREAD

**Issue by tcheval** [Centreon-Widgets/centreon-widget-host-monitoring#9]
We use the action and note url.

With your last update, you force in code "http://" and the link in widget doen't work.
The star and chain open a blank page.

So we have deleted the "http://" and the "str_replace" in table.ihtml and in index.php

table.ihtml
61 : -a target=_blank href='http://{$elem.action_url}'
61 : +a target=_blank href='{$elem.action_url}'

69 : -a target=_blank href='http://{$elem.notes_url}'
69 : +a target=_blank href='{$elem.notes_url}'

index.php     

239 : -$value = str_replace("http://", "", $value);
240 : +$value = urldecode($value);

and it's work. why you use str_replace ?

Thanks

**Comment by mtoufik** [comment]
commit 520f6ac8f5883bfb20f3f395555c0207561c7463

**Comment by kduret** [comment]
Fixed here : https://github.com/Centreon-Widgets/centreon-widget-host-monitoring/issues/8
